apiVersion: v1
kind: Pod
metadata:
  name: doppler-token
spec:
  containers:
    - name: doppler-token
      image: dopplerhq/conf-test
      imagePullPolicy: IfNotPresent

      env:
        - name: DOPPLER_TOKEN
          valueFrom:
            secretKeyRef:
              name: doppler-token
              key: DOPPLER_TOKEN

      resources:
        limits:
          memory: "200Mi"
          cpu: "250m"

  restartPolicy: Never
