apiVersion: v1
kind: Pod
metadata:
  name: doppler-dotenv
spec:
  containers:
    - name: doppler-dotenv
      image: dopplerhq/conf-test      
      imagePullPolicy: IfNotPresent
      command: ["docker-entrypoint.sh"]
      args: ["npm", "start"]

      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /usr/src/app/secrets

      resources:
        limits:
          memory: "200Mi"
          cpu: "250m"

  restartPolicy: Never

  volumes:
    - name: secret-volume
      secret:
        secretName: doppler-dotenv
        items:
          - key: dotenv
            path: .env
