apiVersion: v1
kind: Pod
metadata:
  name: doppler-env-vars
spec:
  containers:
    - name: doppler-env-vars
      image: dopplerhq/conf-test
      imagePullPolicy: IfNotPresent
      command: ["docker-entrypoint.sh"]
      args: ["npm", "start"]

      envFrom:
        - secretRef:
            name: doppler-env-vars

      resources:
        limits:
          memory: "200Mi"
          cpu: "250m"

  restartPolicy: Never
          